---
- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

# The sccache package doesn't exist for apt
- name: Force sccache to be installed from a binary release for Debian-based systems
  ansible.builtin.set_fact:
    sccache_install_from_binary: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Homebrew must compile from source on older versions of macOS, and that takes an
# untenably long time when building sccache.
- name: Force sccache to be installed from a binary release on older macOS systems \
    using Homebrew
  ansible.builtin.set_fact:
    sccache_install_from_binary: true
  when: >
    ansible_distribution_version is version_compare('10.14', '<') and
    ansible_pkg_mgr == "homebrew"

# The sccache package doesn't currently exist on MacPorts
- name: Force sccache to be installed from a binary release when using MacPorts
  ansible.builtin.set_fact:
    sccache_install_from_binary: true
  when: ansible_pkg_mgr == "macports"

- name: Install sccache on Unix
  block:
    - name: Include Unix-specific tasks to install from binary
      ansible.builtin.include_tasks: "unix/install-from-binary.yml"
      when: sccache_install_from_binary

    - name: Include Unix-specific tasks to install via package manager
      ansible.builtin.include_tasks: "install-package-{{ ansible_pkg_mgr }}.yml"
      when: not sccache_install_from_binary

    - name: Include Unix-specific tasks to configure sccache
      ansible.builtin.include_tasks: "unix/configure.yml"
  when: ansible_os_family != "Windows"

- name: Install sccache on Windows
  block:
    - name: Include Windows-specific tasks to install from binary
      ansible.builtin.include_tasks: "windows/install-from-binary.yml"
      when: sccache_install_from_binary

    - name: Include Windows-specific tasks to install via package manager
      ansible.builtin.include_tasks: "install-package-{{ ansible_pkg_mgr }}.yml"
      when: not sccache_install_from_binary

    - name: Include Windows-specific tasks to configure sccache
      ansible.builtin.include_tasks: "windows/configure.yml"
  when: ansible_os_family == "Windows"
