---
- name: Verify sccache configuration for Unix host
  ansible.builtin.include_tasks: "unix/verify-configuration.yml"

- name: Verify sccache configuration for Windows host
  ansible.builtin.include_tasks: "windows/verify-configuration.yml"
