{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && \
    apt-get install -y ca-certificates gnupg python3 python3-apt sudo && \
    apt-get clean

RUN useradd -G sudo -m molecule
# Allow the molecule user to sudo without a password
RUN echo "molecule ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
