---
- name: Ensure sccache configuration directory exists
  become: true
  file:
    path: "{{ sccache_config_directory }}"
    state: directory
    owner: "{{ sccache_user }}"
    mode: "0755"

- name: Create sccache configuration file
  become: true
  template:
    src: config.j2
    dest: "{{ sccache_config_file }}"
    owner: "{{ sccache_user }}"
    mode: "0644"
  notify:
    - Verify sccache configuration for Unix host
