---
- name: Ensure sccache configuration directory exists
  become: true
  file:
    path: "{{ sccache_config_directory }}"
    state: directory
    owner: "{{ sccache_user }}"
    mode: "0755"

- name: Create sccache configuration file
  become: true
  template:
    src: config.j2
    dest: "{{ sccache_config_file }}"
    owner: "{{ sccache_user }}"
    mode: "0644"
  register: sccache_config

- name: Verify sccache configuration
  block:
    - name: Set fact combining install prefix and package manager paths
      set_fact:
        full_path: "{{ sccache_install_prefix_unix }}/bin:{{ ansible_pkg_mgr_path }}"

    # sccache won't load the new values if a server is already running in the background,
    # so we stop any running server before checking the new configuration.
    - name: Shut down running server if present
      command: "sccache --stop-server"  # noqa no-changed-when
      environment:
        PATH: "{{ full_path }}"
      register: stop_server_result
      failed_when:
        - stop_server_result.rc != 0
        # This error occasionally occurs when --stop-server is called on a running server.
        # I'm not sure why sccache doesn't exit gracefully here.
        - '"Failed to send data" not in stop_server_result.stderr'
        # This error occurs if no server was running to begin with.
        - '"couldn''t connect to server" not in stop_server_result.stderr'

    - name: Test configuration by getting stats
      command: "sccache --show-stats"
      environment:
        PATH: "{{ full_path }}"
      changed_when: false
  when: sccache_config is changed
