---
- name: Check sccache version
  ansible.builtin.command: "sccache --version"
  changed_when: false
  failed_when: false
  register: sccache_version_cmd

- name: Initialize should_install_from_binary fact
  ansible.builtin.set_fact:
    should_install_from_binary: false

- name: Set fact to determine if sccache installation is necessary
  ansible.builtin.set_fact:
    should_install_from_binary: true
  when: >
    sccache_version_cmd.rc != 0 or
    sccache_version not in sccache_version_cmd.stdout_lines[0]

- name: Install sccache from GitHub
  when: should_install_from_binary
  block:
    - name: Ensure sccache download and extraction directories exist
      become: true
      ansible.builtin.file:
        path: "{{ sccache_binary_download_dir }}/sccache-v{{ sccache_version }}"
        state: directory
        owner: "{{ sccache_user }}"
        mode: "0755"

    - name: Fetch sccache binary
      ansible.builtin.get_url:
        url: "{{ sccache_download_url }}/v{{ sccache_version }}\
          /sccache-v{{ sccache_version }}-{{ target_triplet }}.tar.gz"
        checksum: "sha256:{{ sccache_download_url }}/v{{ sccache_version }}\
          /sccache-v{{ sccache_version }}-{{ target_triplet }}.tar.gz.sha256"
        dest: "{{ sccache_binary_download_dir }}"
        mode: "0644"

    - name: Uncompress sccache tarball
      ansible.builtin.unarchive:
        src: "{{ sccache_binary_download_dir }}/sccache-v{{ sccache_version }}-\
          {{ target_triplet }}.tar.gz"
        dest: "{{ sccache_binary_download_dir }}/sccache-v{{ sccache_version }}"
        mode: "0755"
        remote_src: true
      environment:
        # unarchive requires GNU tar be installed on macOS, so the Homebrew and MacPorts
        # install paths must be added to PATH in order to find it.
        PATH: "{{ ansible_pkg_mgr_path }}"

    - name: Ensure installation directory exists
      become: true
      ansible.builtin.file:
        path: "{{ sccache_install_prefix_unix }}/bin"
        state: directory
        mode: "0755"

    - name: Install sccache
      become: true
      ansible.builtin.copy:
        src: "{{ sccache_binary_download_dir }}/sccache-v{{ sccache_version }}/\
          sccache-v{{ sccache_version }}-{{ target_triplet }}/sccache"
        dest: "{{ sccache_install_prefix_unix }}/bin/sccache"
        mode: a+rx
        remote_src: true

    - name: Cleanup download directory
      ansible.builtin.file:
        path: "{{ sccache_binary_download_dir }}/sccache-v{{ sccache_version }}"
        state: absent

    - name: Cleanup source tarball
      ansible.builtin.file:
        path: "{{ sccache_binary_download_dir }}/sccache-v{{ sccache_version }}-\
          {{ target_triplet }}.tar.gz"
        state: absent
